FROM maven:3-jdk-11

LABEL maintainer="base2Services"
LABEL SOURCE_REPO="https://github.com/base2Services/build-containers/tree/master/maven-jdk11"

RUN apt-get update && apt-get install protobuf-compiler gettext -y
