FROM public.ecr.aws/aws-observability/aws-otel-collector:v0.15.1

LABEL org.opencontainers.image.source = https://github.com/base2Services/build-containers;

COPY ecs_sd_targets.yaml /etc/ecs_sd_targets.yaml