name: aws-ecs-otel-collector

on:
  push:
    branches: [ master ]
    paths:
    - 'aws-ecs-otel-collector/**'

env:
  IMAGE_NAME: aws-ecs-otel-collector

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: docker build --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" aws-ecs-otel-collector/

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        docker tag $IMAGE_NAME $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
