name: azure-cli

on:
  push:
    branches: [ master ]
    paths:
    - 'azure-cli/**'
    - .github/workflows/azure-cli.yaml

jobs:

  envs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo 
        uses: actions/checkout@v2
      - id: env
        run: |
          output=$(cat azure-cli/version)
          echo "::set-output name=version::$output"
    outputs:
      azure-cli-version: ${{ steps.env.outputs.version }}

  build-and-publish-container-image:
    uses: base2Services/github-workflows/.github/workflows/container-build.yaml@main
    with:
      image-name: azure-cli
      build-args: AZURE_CLI_VERSION=${{ needs.envs.outputs.azure-cli-version }}
