name: cfn-cli

on:
  push:
    branches: [ master ]
    paths:
    - 'cfn-cli/**'
    - .github/workflows/cfn-cli.yaml

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out the repo 
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Repository
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - id: vars
      name: set variables from version file in the directory
      run: |
        output=$(cat cfn-cli/version)
        echo "::set-output name=version::$output"
    
    - name: Build python 3.8 and Push Container Image to GitHub Container Repository
      uses: docker/build-push-action@v3
      with:
        context: ./cfn-cli
        push: true
        tags: |
          ghcr.io/base2services/cfn-cli:latest
          ghcr.io/base2services/cfn-cli:${{ steps.vars.outputs.version }}
        labels: |
          runnumber=${GITHUB_RUN_ID}
          org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}
        build-args: |
          PYTHON_VERSION=3.7
