name: github-backup

on:
  push:
    branches: [ master ]
    paths:
    - 'github-backup/**'
    - .github/workflows/github-backup.yaml

env:
  IMAGE_NAME: github-backup

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: |
        GITHUB_BACKUP_VERSION=$(cat ${IMAGE_NAME}/version)
        docker build --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" --build-arg GITHUB_BACKUP_VERSION=${GITHUB_BACKUP_VERSION} ${IMAGE_NAME}/

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        GITHUB_BACKUP_VERSION=$(cat ${IMAGE_NAME}/version)
        echo "pushing ${IMAGE_NAME} version ${GITHUB_BACKUP_VERSION}"
        docker tag $IMAGE_NAME $IMAGE_ID:latest
        docker tag $IMAGE_NAME $IMAGE_ID:${GITHUB_BACKUP_VERSION}
        docker push $IMAGE_ID:latest
        docker push $IMAGE_ID:${GITHUB_BACKUP_VERSION}
