name: terraform

on:
  push:
    branches: [ master ]
    paths:
    - 'terraform/**'
    - .github/workflows/terraform.yaml

jobs:

  envs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo 
        uses: actions/checkout@v2
      - id: env
        run: |
          output=$(cat terraform/version)
          echo "::set-output name=version::$output"
    outputs:
      terraform-version: ${{ steps.env.outputs.version }}

  build-and-publish-container-image:
    uses: base2Services/github-workflows/.github/workflows/container-build.yaml@main
    with:
      image-name: terraform
      build-args: TERRAFORM_VERSION=${{ needs.envs.outputs.terraform-version }}
