name: test-kitchen

on:
  push:
    branches: [ master ]
    paths:
    - 'test-kitchen/**'
    - .github/workflows/test-kitchen.yaml

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo 
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Repository
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - id: vars
      name: set variables from version file in the directory
      run: |
        output=$(cat test-kitchen/version)
        echo "::set-output name=version::$output"

    - name: Build and Push Container Image to GitHub Container Repository
      uses: docker/build-push-action@v2
      with:
        context: ./test-kitchen
        push: true
        tags: |
          ghcr.io/base2services/test-kitchen:latest
          ghcr.io/base2services/test-kitchen:${{ steps.vars.outputs.version }}
        labels: |
          runnumber=${GITHUB_RUN_ID}
          org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}
        build-args: |
          KITCHEN_VERSION=${{ steps.vars.outputs.version }}